# Generated by Django 4.2.25 on 2025-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0003_alter_review_user_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
