# Generated by Django 4.2.25 on 2025-10-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0005_movie_rating_movie_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='api_id',
        ),
    ]
