# Generated by Django 4.2.25 on 2025-10-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0013_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
