# Generated by Django 4.2.25 on 2025-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0015_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
