# Generated by Django 4.2.25 on 2025-10-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0018_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
